---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Noxlab@Home"
subtitle: "Homelab"
# documentTitle: "Welcome" # Customize the browser tab text
logo: ""
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: false
columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level. 
  headers: # send custom headers when fetching service specific data. Can also be set on a service level.
    Test: "Example"
    Test1: "Example1"


# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

stylesheet:
  - 'assets/catppuccin_frappe.css'

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
# Optional message
# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/NOXLAB-HOME"

# Optional: enable periodic refresh for all smart cards that implements it (unless overriden at service configuration level).
updateIntervalMs: 30000 # interval in milliseconds, minimum is 1000 (1s). Remove or set to 0 to disable. Can be overriden at service level. (default disabled)

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Admin"
    icon: "fas fa-hammer"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    # class: "highlight-purple" # Optional css class to add on the service group. 
    items:
      - name: "Komodo"
        logo: "assets/img/komodo.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Docker management"
        tag: "admin"
        url: "https://server:9120"
        target: "_blank" # optional html tag target attribute
      - name: "Grafana"
        logo: "assets/img/grafana.svg"
        subtitle: "System monitoring"
        tag: "admin"
        url: "https://server/grafana"
      - name: "Traefik"
        logo: "assets/img/traefik.png"
        subtitle: "Reverse-Proxy"
        url: "https://server/traefik/dashboard/"
        tag: "admin"

